apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate1
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      intent: apps1
  template:
    metadata:
      labels:
        intent: apps1
    spec:
      # nodeSelector:
      #   intent: apps
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi