apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  labels:
    intent: apps
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    # - key: karpenter.k8s.aws/instance-size
    #   operator: NotIn
    #   values: [nano, micro, small, medium, large]
    # - key: "karpenter.k8s.aws/instance-category"
    #   operator: In
    #   values: ["c", "m", "r"]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: [medium, large]
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["t"]
    # - key: "karpenter.k8s.aws/instance-cpu"
    #   operator: In
    #   values: ["4", "8", "16", "32"]
    # - key: "karpenter.k8s.aws/instance-hypervisor"
    #   operator: In
    #   values: ["nitro"]
    # - key: karpenter.k8s.aws/instance-generation
    #   operator: Gt
    #   values: ["2"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1c", "us-east-1b"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]

  limits:
    resources:
      cpu: 100
      memory: 100Gi
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  providerRef:
    name: default

---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    Environment: dev111
  securityGroupSelector:
    kubernetes.io/cluster/my-cluster: owned
  tags:
    KarpenerProvisionerName: "default"
    NodeType: "karpenter-workshop"
    IntentLabel: "apps"