name: GitHub Actions Demo Terraform apply
run-name: Deploy Terraform develop environment
on:
  push:
    branches:
      - dev
    paths:
      - '**/*.tf'
jobs:
  networking:
    runs-on: ubuntu-latest
    environment: develop
    env:
      TF_MODULE: networking
    name: Terraform Develop
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false
    - name: Module $TF_MODULE init
      id: init
      run: ./terraform.sh ${GITHUB_REF##*/} $TF_MODULE init
      shell: bash
    - name: Module $TF_MODULE Plan
      id: plan
      run: ./terraform.sh ${GITHUB_REF##*/} $TF_MODULE plan -no-color -out tf.plan
      shell: bash
      continue-on-error: true
    - name: Module $TF_MODULE Apply
      if: github.ref != 'refs/heads/main' && github.event_name == 'push'
      run: ./terraform.sh ${GITHUB_REF##*/} $TF_MODULE apply -input=false tf.plan
      shell: bash

  eks:
    runs-on: ubuntu-latest
    environment: develop
    env:
      TF_MODULE: eks
    name: Terraform Develop
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        terraform_wrapper: false
    - name: Module eks init
      id: init
      run: ./terraform.sh ${GITHUB_REF##*/} $TF_MODULE init
      shell: bash
    - name: Module eks Plan
      id: plan
      run: ./terraform.sh ${GITHUB_REF##*/} $TF_MODULE plan -no-color -out tf.plan
      shell: bash
      continue-on-error: true
